# Generated by Django 4.1.6 on 2023-02-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_alter_category_options_meal_category_meal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
