# Generated by Django 4.1.6 on 2023-02-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0006_alter_category_options_category_slug_meal_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name=0),
            preserve_default=False,
        ),
    ]
