# Generated by Django 4.1.6 on 2023-02-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0007_alter_meal_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
